swagger: '2.0'
info:
  title: Phoenix price API - gRPC Gateway docs
  description: A REST interface for price and trade queries
  version: 1.0.0
paths:
  /tickers:
    get:
      summary: Tickers provides 24-hour pricing and volume information.
      operationId: Tickers
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              type: object
              properties:
                ticker_id:
                  type: string
                base_currency:
                  type: string
                target_currency:
                  type: string
                pool_id:
                  type: string
                last_price:
                  type: string
                base_volume:
                  type: string
                target_volume:
                  type: string
                liquidity_in_usd:
                  type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      tags:
        - TickerQuery
  /historical_trades:
    get:
      summary: >-
        Trades is used to return data on historical completed trades for a given
        market pair.
      operationId: Trades
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              type: object
              properties:
                trade_id:
                  type: string
                price:
                  type: string
                base_volume:
                  type: string
                target_volume:
                  type: string
                trade_timestamp:
                  type: string
                  format: uint64
                type:
                  type: string
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    '@type':
                      type: string
                  additionalProperties: {}
      parameters:
        - name: tickerId
          in: query
          required: false
          type: string
        - name: type
          in: query
          required: false
          type: string
        - name: limit
          in: query
          required: false
          type: integer
          format: int64
        - name: startTime
          in: query
          required: false
          type: string
          format: uint64
        - name: endTime
          in: query
          required: false
          type: string
          format: uint64
      tags:
        - TradeQuery
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            '@type':
              type: string
          additionalProperties: {}
  tickerTickerInfo:
    type: object
    properties:
      ticker_id:
        type: string
      base_currency:
        type: string
      target_currency:
        type: string
      pool_id:
        type: string
      last_price:
        type: string
      base_volume:
        type: string
      target_volume:
        type: string
      liquidity_in_usd:
        type: string
  tickerTickersResponse:
    type: object
    properties:
      tickers:
        type: array
        items:
          type: object
          properties:
            ticker_id:
              type: string
            base_currency:
              type: string
            target_currency:
              type: string
            pool_id:
              type: string
            last_price:
              type: string
            base_volume:
              type: string
            target_volume:
              type: string
            liquidity_in_usd:
              type: string
  tradeTradeInfo:
    type: object
    properties:
      trade_id:
        type: string
      price:
        type: string
      base_volume:
        type: string
      target_volume:
        type: string
      trade_timestamp:
        type: string
        format: uint64
      type:
        type: string
  tradeTradesResponse:
    type: object
    properties:
      trades:
        type: array
        items:
          type: object
          properties:
            trade_id:
              type: string
            price:
              type: string
            base_volume:
              type: string
            target_volume:
              type: string
            trade_timestamp:
              type: string
              format: uint64
            type:
              type: string
