// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: user/query.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	UserQuery_Activities_FullMethodName = "/user.UserQuery/Activities"
)

// UserQueryClient is the client API for UserQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserQueryClient interface {
	Activities(ctx context.Context, in *ActivitiesRequest, opts ...grpc.CallOption) (*ActivitiesResponse, error)
}

type userQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewUserQueryClient(cc grpc.ClientConnInterface) UserQueryClient {
	return &userQueryClient{cc}
}

func (c *userQueryClient) Activities(ctx context.Context, in *ActivitiesRequest, opts ...grpc.CallOption) (*ActivitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivitiesResponse)
	err := c.cc.Invoke(ctx, UserQuery_Activities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserQueryServer is the server API for UserQuery service.
// All implementations must embed UnimplementedUserQueryServer
// for forward compatibility
type UserQueryServer interface {
	Activities(context.Context, *ActivitiesRequest) (*ActivitiesResponse, error)
	mustEmbedUnimplementedUserQueryServer()
}

// UnimplementedUserQueryServer must be embedded to have forward compatible implementations.
type UnimplementedUserQueryServer struct {
}

func (UnimplementedUserQueryServer) Activities(context.Context, *ActivitiesRequest) (*ActivitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Activities not implemented")
}
func (UnimplementedUserQueryServer) mustEmbedUnimplementedUserQueryServer() {}

// UnsafeUserQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserQueryServer will
// result in compilation errors.
type UnsafeUserQueryServer interface {
	mustEmbedUnimplementedUserQueryServer()
}

func RegisterUserQueryServer(s grpc.ServiceRegistrar, srv UserQueryServer) {
	s.RegisterService(&UserQuery_ServiceDesc, srv)
}

func _UserQuery_Activities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserQueryServer).Activities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserQuery_Activities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserQueryServer).Activities(ctx, req.(*ActivitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserQuery_ServiceDesc is the grpc.ServiceDesc for UserQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserQuery",
	HandlerType: (*UserQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Activities",
			Handler:    _UserQuery_Activities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/query.proto",
}
